# Generated by Django 5.0.7 on 2024-07-16 23:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 23, 1, 1, 796220, tzinfo=datetime.timezone.utc), verbose_name='expiration_date'),
        ),
    ]
